### ISSUE TITLE
Means by which to track which model a cloned model came from

### ISSUE THREAD

**Issue by benswinburne** [anfischer/cloner#2]
## Detailed description

I want to keep track of the original id (or whole model perhaps) when cloning a node.

## Context

I have an intermediary model which stores the ids of two models in order to connect them, literally names Connection.

A `Diagram` hasMany `Node`s which are connected by `Connection`s.

A `Connection` has the following columns, `diagram_id`, `source_id`, `destination_id`.

The problem is such that if I clone my `Diagram` with the `nodes` relationship loaded, I get a new diagram and new nodes as expected, however I am unable to clone Connection models because I don't know which `source_id` and `destination_id` to change to from new to cloned.

This change would allow me (and others) to iterate over my table with which contains references to models I have just cloned and make copies of rows. It is useful because not all data has a direct eloquent relationship.

## Possible implementation

I've looked at a couple of ways of doing this but pretty much ruled out the neater one unfortunately.

By changing the current cloning (example below just applies it to the first clone for arguments sake) I can place the original id on the original properties of the model. The problem with this is as soon as you persist the clone Laravel syncs attributes and original gets overwritten.

```
    /**
     * Clones a model and its relationships
     *
     * @param Model $model
     * @return Model
     */
    public function clone(Model $model) : Model
    {
        $replicated = $model->replicate();
        $attributes = $replicated->getAttributes();

        $replicated->setRawAttributes([$model->getKeyName() => $model->getKey()], true);
        $replicated->setRawAttributes($attributes);

        return $this->cloneRecursive($replicated);
    }
```

I looked at storing it on the original property of the model because eloquent intercepts setting actual object properties and stores them in attributes so without modifying the model class and setting a `public $originalModel = null` property we can't set values directly on the model object.

The only other option I've thought of but not experimented with so far is to keep track of a cloned/persisted map within cloner itself. I.e every time a Model gets cloned, cloner stores the model type, the original id and the new id; clone(Model->id 1 into Model->id 2)

```
$cloneMap = [
  App\Model::class => [1 => 2]
];
```

Or something along these lines.

What're your thoughts?

**Comment by benswinburne** [comment]
@anfischer it'd be great to get your feedback on the draft PR if possible. I'm keen to implement something like this in my app so if this is roughly the right direction and something you'd consider merging I can build off of my fork while we finalise things/when you've got time to look at it in more detail.

Similarly if this is something you're unlikely to ever consider/merge I can continue with my fork as I understand this might be something you don't need.

Thanks for your time.

**Comment by anfischer** [comment]
@benswinburne, I think your suggestion is a great improvement to the package and I see no reason to not add the feature.

I will get back to you with feedback on your implementation suggestion when possible. Is your PR  functional for the use case yet?

Thank you too for putting time into the project.

**Comment by benswinburne** [comment]
@anfischer, thanks for the quick response. It allows me to move on with a prototype of a feature in my app now that I know we can move forward in some way with this.

The PR is marked as draft mostly as it is awaiting feedback. It probably needs some docblock comments here and there and I missed a method off of an interface but it works for the purpose intended as far as i can tell.

At some point this week I'll build out the prototype of my feature I need in my app against this fork which should give it a bit more robust use case testing too.

**Comment by benswinburne** [comment]
Just to update you on this, I built the feature using this over the weekend so it'll get peer reviewed and presumably deployed early this week. Other than the fact that I found myself converting to collections a lot (which I've now implemented in Cloner itself instead) the implementation was sufficient and easy to use.

The API of the PR is simple thus far, and just provides a store for `old`->`new`.

I was thinking a further iteration may be useful such that the map is an object which provides methods to find a new ID by old ID and visa versa (as the former is something i've used already in my implementation).

**Comment by benswinburne** [comment]
Hi @anfischer 

We've been using this in production for a couple of months now with no issues.

Are you able to provide any feedback on the PR in the hope we can move forward with getting this or something similar merged? I'm pulling our releases from my fork straight from github at present so I'm hoping to get that organised.

In the event that you're not keen on merging I'll just tag my fork and maintain that as I don't want to push you to use your time.

Thanks very much

Ben

**Comment by anfischer** [comment]
Hi @benswinburne 

Thank you for your patience - I am sorry to once again have been very slow at getting back to you.

Are the two PR's up to date with everything with all changes? (I see you have the branch "keep-track-of-original" on your fork with some additional commits)?

I think it all looks good otherwise and ready for merging and tagging a new release.

**Comment by benswinburne** [comment]
Hi @anfischer, no problem. I'll move the conversation to the respective PRs to avoid any confusion
